--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.435.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 23/02/2021 17:17:58
-- Server version: 10.1.38
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE techno;

--
-- Drop procedure `Deletetutorials`
--
DROP PROCEDURE IF EXISTS Deletetutorials;

--
-- Drop procedure `GetAlltutorials`
--
DROP PROCEDURE IF EXISTS GetAlltutorials;

--
-- Drop procedure `Getonetutorial`
--
DROP PROCEDURE IF EXISTS Getonetutorial;

--
-- Drop procedure `Getonetutorials`
--
DROP PROCEDURE IF EXISTS Getonetutorials;

--
-- Drop procedure `GetRole`
--
DROP PROCEDURE IF EXISTS GetRole;

--
-- Drop procedure `SaveTutorials`
--
DROP PROCEDURE IF EXISTS SaveTutorials;

--
-- Drop procedure `Updatetutorials`
--
DROP PROCEDURE IF EXISTS Updatetutorials;

--
-- Drop table `tutorial`
--
DROP TABLE IF EXISTS tutorial;

--
-- Set default database
--
USE techno;

--
-- Create table `tutorial`
--
CREATE TABLE tutorial (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  status BIT(1) DEFAULT NULL,
  Deleted BIT(1) DEFAULT NULL,
  CreatedAt DATETIME DEFAULT NULL,
  UpdatedAt DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

DELIMITER $$

--
-- Create procedure `Updatetutorials`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Updatetutorials(IN `_title` VARCHAR(128), IN `__description` VARCHAR(128), IN `_Id` BIGINT, IN `_status` VARCHAR(50))
  NO SQL
BEGIN

UPDATE tutorial
SET title = _title,
    description = __description,
    UpdatedAt = NOW(),
    status = _status
WHERE id = _Id;
END
$$

--
-- Create procedure `SaveTutorials`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE SaveTutorials(IN `_title` VARCHAR(50), IN `_description` VARCHAR(128) )
  NO SQL
BEGIN

INSERT INTO `tutorial` (`title`, `description`, `status`, `CreatedAt`, `UpdatedAt`, `Deleted`)
  VALUES (_title, _description, 0, NOW(), NOW(), 0);

END
$$

--
-- Create procedure `GetRole`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE GetRole(IN `_Id` BIGINT)
  NO SQL
BEGIN
SELECT
  *
FROM tutorial
WHERE id = _Id;
END
$$

--
-- Create procedure `Getonetutorials`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Getonetutorials(IN `_Id` BIGINT)
  NO SQL
BEGIN
SELECT
  *
FROM tutorial
WHERE id = _Id;
END
$$

--
-- Create procedure `Getonetutorial`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Getonetutorial(IN `_Id` BIGINT)
  NO SQL
BEGIN
SELECT
  *
FROM tutorial
WHERE id = _Id;
END
$$

--
-- Create procedure `GetAlltutorials`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE GetAlltutorials()
BEGIN
SELECT
  id,
  title,
  description,
  status
FROM tutorial
WHERE Deleted = 0;
END
$$

--
-- Create procedure `Deletetutorials`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Deletetutorials(IN `_Id` BIGINT )
  NO SQL
BEGIN

UPDATE tutorial
SET Deleted = 1
WHERE id = _Id;


END
$$

DELIMITER ;

-- 
-- Dumping data for table tutorial
--
INSERT INTO tutorial VALUES
(1, 'kelvin', 'chemei', True, False, '2021-02-23 16:42:43', '2021-02-23 16:58:26');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;